version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/bookmarklets
    steps:
      - checkout
      - deploy:
          command: |
            sudo apt-get install -y awscli
            aws s3 sync bookmarklets s3://swfz-bookmarklets/bookmarklets/ --delete

